use coritos_db;
INSERT INTO song (number, title, type_coro) VALUES (1, '1. ¡Santo! ¡Santo! ¡Santo!', 3);
INSERT INTO song (number, title, type_coro) VALUES (2, '2. ¡Oh Padre, Eterno Dios!', 3);
INSERT INTO song (number, title, type_coro) VALUES (3, '3. Te Loamos, ¡Oh Dios!', 3);
INSERT INTO song (number, title, type_coro) VALUES (4, '4. A Dios El Padre Celestial', 3);
INSERT INTO song (number, title, type_coro) VALUES (5, '5. A Nuestro Padre Dios', 3);
INSERT INTO song (number, title, type_coro) VALUES (6, '6. Que Todo El Mundo Cante Al Señor', 3);
INSERT INTO song (number, title, type_coro) VALUES (7, '7. Solo A Ti, Dios Y Señor', 3);
INSERT INTO song (number, title, type_coro) VALUES (8, '8. Alabad, Oh Los Siervos Del Señor', 3);
INSERT INTO song (number, title, type_coro) VALUES (9, '9. Señor, ¿Quien Entrará?', 3);
INSERT INTO song (number, title, type_coro) VALUES (10, '10. Hoy Canto El Gran Poder De Dios', 3);
INSERT INTO song (number, title, type_coro) VALUES (11, '11. Bendice, Oh Alma A Tu Creador', 3);
INSERT INTO song (number, title, type_coro) VALUES (12, '12. Dad A Dios Inmortal Alabanza', 3);
INSERT INTO song (number, title, type_coro) VALUES (13, '13. Engrandecido Sea Jehová', 3);
INSERT INTO song (number, title, type_coro) VALUES (14, '14. Dios Está Presente', 3);
INSERT INTO song (number, title, type_coro) VALUES (15, '15. Nunca, Dios Mío', 3);
INSERT INTO song (number, title, type_coro) VALUES (16, '16. Engrandecido Sea Dios', 3);
INSERT INTO song (number, title, type_coro) VALUES (17, '17. Todos Juntos Tributemos', 3);
INSERT INTO song (number, title, type_coro) VALUES (18, '18. Corazones Te Ofrecemos', 3);
INSERT INTO song (number, title, type_coro) VALUES (19, '19. Salmo 100', 3);
INSERT INTO song (number, title, type_coro) VALUES (20, '20. ¡Cuan Grande Es Él!', 3);
INSERT INTO song (number, title, type_coro) VALUES (21, '21. Alabad Al Señor', 3);
INSERT INTO song (number, title, type_coro) VALUES (22, '22. A Dios Demos Gloria', 3);
INSERT INTO song (number, title, type_coro) VALUES (23, '23. Cuanto Soy Y Cuanto Encierro', 3);
INSERT INTO song (number, title, type_coro) VALUES (24, '24. Honor, Loor Y Gloria', 3);
INSERT INTO song (number, title, type_coro) VALUES (25, '25. Santo Dios, Te Damos Loor', 3);
INSERT INTO song (number, title, type_coro) VALUES (26, '26. Castillo Fuerte Es Nuestro Dios', 3);
INSERT INTO song (number, title, type_coro) VALUES (27, '27. A Dios, Naciones, Dad Loor', 3);
INSERT INTO song (number, title, type_coro) VALUES (28, '28. Bendice, ¡Oh Alma Mía!', 3);
INSERT INTO song (number, title, type_coro) VALUES (29, '29. Venid, Nuestras Voces Alegres Unamos', 3);
INSERT INTO song (number, title, type_coro) VALUES (30, '30. Gloría Demos Al Salvador', 3);
INSERT INTO song (number, title, type_coro) VALUES (31, '31. Ved Al Cristo, Rey De Gloria', 3);
INSERT INTO song (number, title, type_coro) VALUES (32, '32. Redentor, Te Adoramos', 3);
INSERT INTO song (number, title, type_coro) VALUES (33, '33. Loores Dad A Cristo El Rey', 3);
INSERT INTO song (number, title, type_coro) VALUES (34, '34. Digno Es El Cordero', 3);
INSERT INTO song (number, title, type_coro) VALUES (35, '35. Fuente De La Vida Eterna', 3);
INSERT INTO song (number, title, type_coro) VALUES (36, '36. Gloria A Tu Nombre', 3);
INSERT INTO song (number, title, type_coro) VALUES (37, '37. ¡Dad Gracias Y Hoy Cantad!', 3);
INSERT INTO song (number, title, type_coro) VALUES (38, '38. ¡Gloria! ¡Gloria!', 3);
INSERT INTO song (number, title, type_coro) VALUES (39, '39. Santo Nombre Alabare', 3);
INSERT INTO song (number, title, type_coro) VALUES (40, '40. Te Amo', 3);
INSERT INTO song (number, title, type_coro) VALUES (41, '41. Me Agrada Cantar', 3);
INSERT INTO song (number, title, type_coro) VALUES (42, '42. La Canción Al Mundo Entonad', 3);
INSERT INTO song (number, title, type_coro) VALUES (43, '43. De Quien Pago Mi Redención', 3);
INSERT INTO song (number, title, type_coro) VALUES (44, '44. Con Canticos, Señor', 3);
INSERT INTO song (number, title, type_coro) VALUES (45, '45. A Jesús Alabaremos', 3);
INSERT INTO song (number, title, type_coro) VALUES (46, '46. Maravilloso Es El Nombre De Jesús', 3);
INSERT INTO song (number, title, type_coro) VALUES (47, '47. Jesús Es Mi Rey Soberano', 3);
INSERT INTO song (number, title, type_coro) VALUES (48, '48. Gracias Dad A Jesucristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (49, '49. Es Cristo Quien Por Mi Murió', 3);
INSERT INTO song (number, title, type_coro) VALUES (50, '50. Cantad Alegres Al Señor', 3);
INSERT INTO song (number, title, type_coro) VALUES (51, '51. Por La Excelsa Majestad', 3);
INSERT INTO song (number, title, type_coro) VALUES (52, '52. Cristo, Yo Quiero Dar Gracias', 3);
INSERT INTO song (number, title, type_coro) VALUES (53, '53. Cristo Divino, Hijo Unigénito', 3);
INSERT INTO song (number, title, type_coro) VALUES (54, '54. Oh Ven, Emanuel', 3);
INSERT INTO song (number, title, type_coro) VALUES (55, '55. Consolaos, Pueblo Mío', 3);
INSERT INTO song (number, title, type_coro) VALUES (56, '56. Ven, Jesús Muy Esperado', 3);
INSERT INTO song (number, title, type_coro) VALUES (57, '57. En Belén Nació Jesús', 3);
INSERT INTO song (number, title, type_coro) VALUES (58, '58. Noche De Paz', 3);
INSERT INTO song (number, title, type_coro) VALUES (59, '59. En La Noche Los Pastores Velan', 3);
INSERT INTO song (number, title, type_coro) VALUES (60, '60. Tu Dejaste Tu Trono Y Corona Por Mi', 3);
INSERT INTO song (number, title, type_coro) VALUES (61, '61. Pastores Cerca De Belén', 3);
INSERT INTO song (number, title, type_coro) VALUES (62, '62. Hoy La Nueva Dad', 3);
INSERT INTO song (number, title, type_coro) VALUES (63, '63. Venid, Pastores', 3);
INSERT INTO song (number, title, type_coro) VALUES (64, '64. Se Oye Un Son En Alta Esfera', 3);
INSERT INTO song (number, title, type_coro) VALUES (65, '65. En Un Pesebre Yace Un Niñito', 3);
INSERT INTO song (number, title, type_coro) VALUES (66, '66. Cristianos, Hoy Cantad A Dios', 3);
INSERT INTO song (number, title, type_coro) VALUES (67, '67. Ángeles Cantando Están', 3);
INSERT INTO song (number, title, type_coro) VALUES (68, '68. A Media Noche Resonó', 3);
INSERT INTO song (number, title, type_coro) VALUES (69, '69. Ángeles De Alta Gloria', 3);
INSERT INTO song (number, title, type_coro) VALUES (70, '70. Venid, Pastorcitos', 3);
INSERT INTO song (number, title, type_coro) VALUES (72, '72. Venid, Fieles Todos', 3);
INSERT INTO song (number, title, type_coro) VALUES (71, '71. Cantan Ángeles Mil', 3);
INSERT INTO song (number, title, type_coro) VALUES (73, '73. Ve, Dilo En Las Montañas', 3);
INSERT INTO song (number, title, type_coro) VALUES (74, '74. ¡Oh Aldehuela De Belén!', 3);
INSERT INTO song (number, title, type_coro) VALUES (75, '75. La Noticia Sin Igual', 3);
INSERT INTO song (number, title, type_coro) VALUES (76, '76. ¡Al Mundo Paz, Nació Jesús!', 3);
INSERT INTO song (number, title, type_coro) VALUES (77, '77. Villancico De La Estrella', 3);
INSERT INTO song (number, title, type_coro) VALUES (78, '78. Un Canto De Belen Cantad', 3);
INSERT INTO song (number, title, type_coro) VALUES (79, '79. Niño Santo, Sufres Tanto', 3);
INSERT INTO song (number, title, type_coro) VALUES (80, '80. Venid A Belén', 3);
INSERT INTO song (number, title, type_coro) VALUES (81, '81. Venid, Pastorcillos', 3);
INSERT INTO song (number, title, type_coro) VALUES (82, '82. Jesucristo Hoy Nació', 3);
INSERT INTO song (number, title, type_coro) VALUES (83, '83. ¿Que Niño Es Este?', 3);
INSERT INTO song (number, title, type_coro) VALUES (84, '84. ¡Oh Santísimo, Felicísimo!', 3);
INSERT INTO song (number, title, type_coro) VALUES (85, '85. Allá En El Pesebre', 3);
INSERT INTO song (number, title, type_coro) VALUES (86, '86. Suenen Dulces Himnos', 3);
INSERT INTO song (number, title, type_coro) VALUES (87, '87. Dad Loor A Dios', 3);
INSERT INTO song (number, title, type_coro) VALUES (88, '88. Eres Del Mundo', 3);
INSERT INTO song (number, title, type_coro) VALUES (89, '89. Cuando Oigo La Historia De Jesús', 3);
INSERT INTO song (number, title, type_coro) VALUES (90, '90. Del Santo Amor De Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (91, '91. ¡Oh Maestro Y Mi Señor!', 3);
INSERT INTO song (number, title, type_coro) VALUES (92, '92. Hijo De Dios Es Él', 3);
INSERT INTO song (number, title, type_coro) VALUES (93, '93. La Tierna Voz Del Salvador', 3);
INSERT INTO song (number, title, type_coro) VALUES (94, '94. Tierra De La Palestina', 3);
INSERT INTO song (number, title, type_coro) VALUES (95, '95. Contemplando Tu Amor', 3);
INSERT INTO song (number, title, type_coro) VALUES (96, '96. El Padre Nuestro', 3);
INSERT INTO song (number, title, type_coro) VALUES (97, '97. ¡Oh Rostro Ensangrentado!', 3);
INSERT INTO song (number, title, type_coro) VALUES (98, '98. Hay Una Fuente Sin Igual', 3);
INSERT INTO song (number, title, type_coro) VALUES (99, '99. En El Calvario Estuve Yo', 3);
INSERT INTO song (number, title, type_coro) VALUES (100, '100. En El Monte Calvario', 3);
INSERT INTO song (number, title, type_coro) VALUES (101, '101. Cristo Su Preciosa Sangre', 3);
INSERT INTO song (number, title, type_coro) VALUES (102, '102. Jesucristo Fue Inmolado', 3);
INSERT INTO song (number, title, type_coro) VALUES (103, '103. Al Salvador Jesús', 3);
INSERT INTO song (number, title, type_coro) VALUES (104, '104. De Tal Manera Me Amo', 3);
INSERT INTO song (number, title, type_coro) VALUES (105, '105. Rey De Mi Vida', 3);
INSERT INTO song (number, title, type_coro) VALUES (106, '106. Espinas De Mi Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (107, '107. Manos Cariñosas', 3);
INSERT INTO song (number, title, type_coro) VALUES (108, '108. Mi Bendito Redentor', 3);
INSERT INTO song (number, title, type_coro) VALUES (109, '109. La Cruz Excelsa Al Contemplar', 3);
INSERT INTO song (number, title, type_coro) VALUES (110, '110. En La Cruz', 3);
INSERT INTO song (number, title, type_coro) VALUES (111, '111. En La Vergonzosa Cruz', 3);
INSERT INTO song (number, title, type_coro) VALUES (112, '112. Inmensa Y Sin Igual Piedad', 3);
INSERT INTO song (number, title, type_coro) VALUES (113, '113. Vuestro Himno Hoy Cantad', 3);
INSERT INTO song (number, title, type_coro) VALUES (114, '114. El Señor Resucito', 3);
INSERT INTO song (number, title, type_coro) VALUES (115, '115. Jesucristo Resucito', 3);
INSERT INTO song (number, title, type_coro) VALUES (116, '116. Un Día', 3);
INSERT INTO song (number, title, type_coro) VALUES (117, '117. Herido, Triste, A Jesús', 3);
INSERT INTO song (number, title, type_coro) VALUES (118, '118. ¿Viste Tu?', 3);
INSERT INTO song (number, title, type_coro) VALUES (119, '119. El Día Del Señor', 3);
INSERT INTO song (number, title, type_coro) VALUES (120, '120. Alegres Cantemos Canciones De Loor', 3);
INSERT INTO song (number, title, type_coro) VALUES (121, '121. Oh Hermanos, Dad A Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (122, '122. Jesús Venció La Muerte', 3);
INSERT INTO song (number, title, type_coro) VALUES (123, '123. Se Levantó El Señor', 3);
INSERT INTO song (number, title, type_coro) VALUES (124, '124. Tuya Es La Gloria', 3);
INSERT INTO song (number, title, type_coro) VALUES (125, '125. La Tumba Le Encerró', 3);
INSERT INTO song (number, title, type_coro) VALUES (126, '126. El Rey Ya Viene', 3);
INSERT INTO song (number, title, type_coro) VALUES (128, '128. Cristianos Todos, A Prepararse', 3);
INSERT INTO song (number, title, type_coro) VALUES (127, '127. Viene Otra Vez', 3);
INSERT INTO song (number, title, type_coro) VALUES (129, '129. Día De Victoria', 3);
INSERT INTO song (number, title, type_coro) VALUES (130, '130. ¡Oh Dios, Que Mañana!', 3);
INSERT INTO song (number, title, type_coro) VALUES (131, '131. Cristo Viene', 3);
INSERT INTO song (number, title, type_coro) VALUES (132, '132. Yo Solo Espero Ese Día', 3);
INSERT INTO song (number, title, type_coro) VALUES (133, '133. Santo Espíritu, Se Mi Guía', 3);
INSERT INTO song (number, title, type_coro) VALUES (134, '134. ¡Santo Espíritu, Lléname!', 3);
INSERT INTO song (number, title, type_coro) VALUES (135, '135. Ven, Santo Espíritu', 3);
INSERT INTO song (number, title, type_coro) VALUES (136, '136. Llena, Oh Santo Espíritu', 3);
INSERT INTO song (number, title, type_coro) VALUES (137, '137. Espíritu De Amor', 3);
INSERT INTO song (number, title, type_coro) VALUES (138, '138. Divino Espíritu De Dios', 3);
INSERT INTO song (number, title, type_coro) VALUES (139, '139. Santo Espíritu, Fluye En Mi', 3);
INSERT INTO song (number, title, type_coro) VALUES (140, '140. Espíritu De Luz Y Amor', 3);
INSERT INTO song (number, title, type_coro) VALUES (141, '141. Dicha Grande Es La Del Hombre', 3);
INSERT INTO song (number, title, type_coro) VALUES (142, '142. Padre, Tu Palabra Es', 3);
INSERT INTO song (number, title, type_coro) VALUES (143, '143. Bellas Palabras De Vida', 3);
INSERT INTO song (number, title, type_coro) VALUES (144, '144. Gozo La Santa Palabra Al Leer', 3);
INSERT INTO song (number, title, type_coro) VALUES (145, '145. Tu Palabra Es Divina Y Santa', 3);
INSERT INTO song (number, title, type_coro) VALUES (146, '146. Santa Biblia Para Mi', 3);
INSERT INTO song (number, title, type_coro) VALUES (147, '147. La Ley De Dios Perfecta Es', 3);
INSERT INTO song (number, title, type_coro) VALUES (148, '148. La Escalera De Jacob', 3);
INSERT INTO song (number, title, type_coro) VALUES (149, '149. Omnipotente Padre Dios', 3);
INSERT INTO song (number, title, type_coro) VALUES (150, '150. Por Los Santos Que Descansan Ya', 3);
INSERT INTO song (number, title, type_coro) VALUES (151, '151. Oh Juventud, Que Alabas Al Señor', 3);
INSERT INTO song (number, title, type_coro) VALUES (153, '153. La Creación', 3);
INSERT INTO song (number, title, type_coro) VALUES (152, '152. Señor Jehová, Omnipotente Dios', 3);
INSERT INTO song (number, title, type_coro) VALUES (154, '154. El Mundo Entero Es Del Padre', 3);
INSERT INTO song (number, title, type_coro) VALUES (155, '155. Alcemos Nuestra Voz', 3);
INSERT INTO song (number, title, type_coro) VALUES (156, '156. Siempre Amanece', 3);
INSERT INTO song (number, title, type_coro) VALUES (157, '157. ¿Has Hallado En Cristo?', 3);
INSERT INTO song (number, title, type_coro) VALUES (158, '158. Rey De Reyes', 3);
INSERT INTO song (number, title, type_coro) VALUES (159, '159. Roca De La Eternidad', 3);
INSERT INTO song (number, title, type_coro) VALUES (160, '160. ¿Qué Me Puede Dar Perdón?', 3);
INSERT INTO song (number, title, type_coro) VALUES (161, '161. Bendito Dios', 3);
INSERT INTO song (number, title, type_coro) VALUES (162, '162. Todos Los Que Tengan Sed', 3);
INSERT INTO song (number, title, type_coro) VALUES (163, '163. Todos Los Que Tengan Sed', 3);
INSERT INTO song (number, title, type_coro) VALUES (164, '164. Amigo Halle', 3);
INSERT INTO song (number, title, type_coro) VALUES (165, '165. Jesús Es La Luz Del Mundo', 3);
INSERT INTO song (number, title, type_coro) VALUES (166, '166. Cariñoso Salvador', 3);
INSERT INTO song (number, title, type_coro) VALUES (167, '167. Cariñoso Salvador', 3);
INSERT INTO song (number, title, type_coro) VALUES (168, '168. Salvante Amor', 3);
INSERT INTO song (number, title, type_coro) VALUES (169, '169. Levantado Fue Jesús', 3);
INSERT INTO song (number, title, type_coro) VALUES (170, '170. ¿Quieres Ser Salvo De Toda Maldad?', 3);
INSERT INTO song (number, title, type_coro) VALUES (171, '171. La Cruz Solo Me Guiará', 3);
INSERT INTO song (number, title, type_coro) VALUES (172, '172. Mi Culpa El Llevo', 3);
INSERT INTO song (number, title, type_coro) VALUES (173, '173. Tanto Al Mundo Dios Amo', 3);
INSERT INTO song (number, title, type_coro) VALUES (174, '174. Con Alma Y Voz Te Alabaré', 3);
INSERT INTO song (number, title, type_coro) VALUES (175, '175. Por Su Misericordia', 3);
INSERT INTO song (number, title, type_coro) VALUES (176, '176. Años Mi Alma En Vanidad Vivió', 3);
INSERT INTO song (number, title, type_coro) VALUES (177, '177. Grande Amor, Sublime Eterno', 3);
INSERT INTO song (number, title, type_coro) VALUES (178, '178. Vida Abundante', 3);
INSERT INTO song (number, title, type_coro) VALUES (179, '179. Al Que En Busca De La Luz', 3);
INSERT INTO song (number, title, type_coro) VALUES (180, '180. En Una Cruz A Cristo Vi', 3);
INSERT INTO song (number, title, type_coro) VALUES (181, '181. Ten Misericordia De Mí', 3);
INSERT INTO song (number, title, type_coro) VALUES (182, '182. Jesús Me Incluye A Mi', 3);
INSERT INTO song (number, title, type_coro) VALUES (183, '183. Gracia Admirable', 3);
INSERT INTO song (number, title, type_coro) VALUES (184, '184. Gracia Admirable Del Dios De Amor', 3);
INSERT INTO song (number, title, type_coro) VALUES (185, '185. Alabad A Jehová', 3);
INSERT INTO song (number, title, type_coro) VALUES (186, '186. Si Creyere Puede A Él Venir', 3);
INSERT INTO song (number, title, type_coro) VALUES (187, '187. Vengo, Jesús, A Ti', 3);
INSERT INTO song (number, title, type_coro) VALUES (188, '188. 2 Crónicas 7', 3);
INSERT INTO song (number, title, type_coro) VALUES (189, '189. Yo Escucho, Buen Jesús', 3);
INSERT INTO song (number, title, type_coro) VALUES (190, '190. Salvador, A Ti Acudo', 3);
INSERT INTO song (number, title, type_coro) VALUES (191, '191. ¿Qué Harás Tu Con Cristo?', 3);
INSERT INTO song (number, title, type_coro) VALUES (193, '193. Ven, Reina En Mi Corazón', 3);
INSERT INTO song (number, title, type_coro) VALUES (194, '194. El Salvador Te Espera', 3);
INSERT INTO song (number, title, type_coro) VALUES (192, '192. Sin Cristo No Tengo Nada', 3);
INSERT INTO song (number, title, type_coro) VALUES (195, '195. Ven, Amigo, Al Dulce Jesús', 3);
INSERT INTO song (number, title, type_coro) VALUES (196, '196. A Jesucristo Ven Sin Tardar', 3);
INSERT INTO song (number, title, type_coro) VALUES (197, '197. Ven Hoy Al Salvador', 3);
INSERT INTO song (number, title, type_coro) VALUES (198, '198. Cuan Tiernamente Jesús Hoy Nos Llama', 3);
INSERT INTO song (number, title, type_coro) VALUES (199, '199. ¿Sabes Tu De Cristo?', 3);
INSERT INTO song (number, title, type_coro) VALUES (200, '200. Todo Aquel Que Oye', 3);
INSERT INTO song (number, title, type_coro) VALUES (201, '201. Hay Lugar En La Cruz', 3);
INSERT INTO song (number, title, type_coro) VALUES (202, '202. Ven Al Señor Jesús', 3);
INSERT INTO song (number, title, type_coro) VALUES (203, '203. Alguien Está A Mi Puerta', 3);
INSERT INTO song (number, title, type_coro) VALUES (204, '204. Escucha, Amigo, Al Señor', 3);
INSERT INTO song (number, title, type_coro) VALUES (205, '205. La Bondadosa Invitación', 3);
INSERT INTO song (number, title, type_coro) VALUES (206, '206. Ven, Amigo, A Jesús', 3);
INSERT INTO song (number, title, type_coro) VALUES (207, '207. Mi Amor Y Vida', 3);
INSERT INTO song (number, title, type_coro) VALUES (208, '208. Con Voz Benigna Te Llama', 3);
INSERT INTO song (number, title, type_coro) VALUES (209, '209. ¿Te Sientes Casi Resuelto Ya?', 3);
INSERT INTO song (number, title, type_coro) VALUES (210, '210. Tendrás Que Renacer', 3);
INSERT INTO song (number, title, type_coro) VALUES (211, '211. Tal Como Soy', 3);
INSERT INTO song (number, title, type_coro) VALUES (212, '212. ¿Qué Debo Hacer?', 3);
INSERT INTO song (number, title, type_coro) VALUES (213, '213. Tu Amaras A Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (214, '214. Pon Tus Ojos En Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (215, '215. Su Yugo Es Fácil', 3);
INSERT INTO song (number, title, type_coro) VALUES (216, '216. Es Jesús Mi Amante Guía', 3);
INSERT INTO song (number, title, type_coro) VALUES (217, '217. Corazones Siempre Alegres', 3);
INSERT INTO song (number, title, type_coro) VALUES (218, '218. Seguiré Do El Me Guie', 3);
INSERT INTO song (number, title, type_coro) VALUES (219, '219. Oh Dios, Socorro En El Ayer', 3);
INSERT INTO song (number, title, type_coro) VALUES (220, '220. El Que Habita Al Abrigo De Dios', 3);
INSERT INTO song (number, title, type_coro) VALUES (221, '221. Señor Jesús, La Luz Del Sol Se Fue', 3);
INSERT INTO song (number, title, type_coro) VALUES (222, '222. Maravilloso Es', 3);
INSERT INTO song (number, title, type_coro) VALUES (223, '223. A Solas Al Huerto Yo Voy', 3);
INSERT INTO song (number, title, type_coro) VALUES (224, '224. Nuestra Esperanza Está En El Señor', 3);
INSERT INTO song (number, title, type_coro) VALUES (225, '225. ¡Oh Pastor Divino Escucha!', 3);
INSERT INTO song (number, title, type_coro) VALUES (226, '226. Se Tu Mi Visión', 3);
INSERT INTO song (number, title, type_coro) VALUES (227, '227. Me Guía Él, Con Cuanto Amor', 3);
INSERT INTO song (number, title, type_coro) VALUES (228, '228. Me Condujo El Salvador', 3);
INSERT INTO song (number, title, type_coro) VALUES (229, '229. Te Cuidara El Señor', 3);
INSERT INTO song (number, title, type_coro) VALUES (230, '230. Grande Es Tu Fidelidad', 3);
INSERT INTO song (number, title, type_coro) VALUES (231, '231. Mis Ojos A Los Montes Al Redor', 3);
INSERT INTO song (number, title, type_coro) VALUES (232, '232. Pastoréanos, Jesús Amante', 3);
INSERT INTO song (number, title, type_coro) VALUES (233, '233. Hijos Del Padre Celestial', 3);
INSERT INTO song (number, title, type_coro) VALUES (234, '234. Alma, Bendice Al Señor', 3);
INSERT INTO song (number, title, type_coro) VALUES (235, '235. Elevemos Al Creador', 3);
INSERT INTO song (number, title, type_coro) VALUES (236, '236. Cuando Combatido Por La Adversidad', 3);
INSERT INTO song (number, title, type_coro) VALUES (237, '237. ¡Gloria A Dios!', 3);
INSERT INTO song (number, title, type_coro) VALUES (238, '238. Al Trono Majestuoso', 3);
INSERT INTO song (number, title, type_coro) VALUES (239, '239. De Boca Y Corazón', 3);
INSERT INTO song (number, title, type_coro) VALUES (240, '240. En Tu Santo Templo', 3);
INSERT INTO song (number, title, type_coro) VALUES (241, '241. Iglesia De Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (242, '242. Tu Reino Amo, ¡Oh Dios!', 3);
INSERT INTO song (number, title, type_coro) VALUES (243, '243. Bendigamos Al Señor', 3);
INSERT INTO song (number, title, type_coro) VALUES (244, '244. Orar, Trabajar, Testificar', 3);
INSERT INTO song (number, title, type_coro) VALUES (245, '245. Testificando En El Bautismo', 3);
INSERT INTO song (number, title, type_coro) VALUES (246, '246. Soy Un Hombre Bautizado', 3);
INSERT INTO song (number, title, type_coro) VALUES (247, '247. En Las Aguas De La Muerte', 3);
INSERT INTO song (number, title, type_coro) VALUES (248, '248. Pan Tu Eres, Oh Señor', 3);
INSERT INTO song (number, title, type_coro) VALUES (249, '249. ¡Oh Pan Del Cielo, Dulce Bien!', 3);
INSERT INTO song (number, title, type_coro) VALUES (250, '250. En Memoria De Mi', 3);
INSERT INTO song (number, title, type_coro) VALUES (251, '251. Tu Sangre Carmesí', 3);
INSERT INTO song (number, title, type_coro) VALUES (252, '252. Obediente A Tu Mandato', 3);
INSERT INTO song (number, title, type_coro) VALUES (253, '253. Cara A Cara Yo Te Miro Aquí', 3);
INSERT INTO song (number, title, type_coro) VALUES (254, '254. Tu Cena, Oh Dios', 3);
INSERT INTO song (number, title, type_coro) VALUES (255, '255. Ardan Nuestros Corazones', 3);
INSERT INTO song (number, title, type_coro) VALUES (256, '256. Amémonos, Hermanos', 3);
INSERT INTO song (number, title, type_coro) VALUES (257, '257. Después De Haber Oído Tu Palabra', 3);
INSERT INTO song (number, title, type_coro) VALUES (258, '258. Por Los Lazos Del Santo Amor', 3);
INSERT INTO song (number, title, type_coro) VALUES (259, '259. Dulce Espíritu', 3);
INSERT INTO song (number, title, type_coro) VALUES (260, '260. Sagrado Es El Amor', 3);
INSERT INTO song (number, title, type_coro) VALUES (261, '261. Un Mandamiento Nuevo', 3);
INSERT INTO song (number, title, type_coro) VALUES (262, '262. Dios Os Guarde En Su Santo Amor', 3);
INSERT INTO song (number, title, type_coro) VALUES (263, '263. Mándanos Lluvias De Bendición', 3);
INSERT INTO song (number, title, type_coro) VALUES (264, '264. Cerca, Más Cerca', 3);
INSERT INTO song (number, title, type_coro) VALUES (265, '265. Lluvias De Gracia', 3);
INSERT INTO song (number, title, type_coro) VALUES (266, '266. Dios De Gracia, Dios De Gloria', 3);
INSERT INTO song (number, title, type_coro) VALUES (267, '267. Ven, Aviva Mi Alma Con Poder', 3);
INSERT INTO song (number, title, type_coro) VALUES (268, '268. El Fuego Santo', 3);
INSERT INTO song (number, title, type_coro) VALUES (269, '269. A Tu Iglesia, Oh Dios, Da Vida', 3);
INSERT INTO song (number, title, type_coro) VALUES (270, '270. Corona A Nuestro Salvador', 3);
INSERT INTO song (number, title, type_coro) VALUES (271, '271. Avívanos, Señor', 3);
INSERT INTO song (number, title, type_coro) VALUES (272, '272. Tu Obra Aviva, Oh Dios', 3);
INSERT INTO song (number, title, type_coro) VALUES (273, '273. Vida Nueva En Jesús', 3);
INSERT INTO song (number, title, type_coro) VALUES (274, '274. Ven Tu, ¡Oh Rey Eterno!', 3);
INSERT INTO song (number, title, type_coro) VALUES (275, '275. Lo Debes Compartir', 3);
INSERT INTO song (number, title, type_coro) VALUES (276, '276. El Mundo Es Del Señor', 3);
INSERT INTO song (number, title, type_coro) VALUES (277, '277. Oriente Ni Occidente', 3);
INSERT INTO song (number, title, type_coro) VALUES (278, '278. Las Nuevas Dad', 3);
INSERT INTO song (number, title, type_coro) VALUES (279, '279. Oh, Ruégote, Señor, Me Enseñes', 3);
INSERT INTO song (number, title, type_coro) VALUES (280, '280. Lejos Están Viviendo En El Pecado', 3);
INSERT INTO song (number, title, type_coro) VALUES (281, '281. ¡Oh Alzad Vuestros Ojos!', 3);
INSERT INTO song (number, title, type_coro) VALUES (282, '282. Ama A Tus Prójimos', 3);
INSERT INTO song (number, title, type_coro) VALUES (283, '283. Envíame, Señor', 3);
INSERT INTO song (number, title, type_coro) VALUES (284, '284. La Historia De Cristo Diremos', 3);
INSERT INTO song (number, title, type_coro) VALUES (285, '285. Id Y Dad Las Nuevas', 3);
INSERT INTO song (number, title, type_coro) VALUES (286, '286. Salgamos, Fieles, A Anunciar', 3);
INSERT INTO song (number, title, type_coro) VALUES (287, '287. Envíame A Mi', 3);
INSERT INTO song (number, title, type_coro) VALUES (288, '288. Haz Arder Mi Alma', 3);
INSERT INTO song (number, title, type_coro) VALUES (289, '289. De Su Alto Solio Celestial', 3);
INSERT INTO song (number, title, type_coro) VALUES (290, '290. Canta A Dios Con Alegría', 3);
INSERT INTO song (number, title, type_coro) VALUES (291, '291. Jehová Es Mi Luz Y Mi Salvación', 3);
INSERT INTO song (number, title, type_coro) VALUES (292, '292. ¡Oh Cristo De Infinito Amor', 3);
INSERT INTO song (number, title, type_coro) VALUES (293, '293. Mil Gracias Por Tu Orden', 3);
INSERT INTO song (number, title, type_coro) VALUES (294, '294. Vamos A Sembrar', 3);
INSERT INTO song (number, title, type_coro) VALUES (295, '295. Así Os Mando Yo', 3);
INSERT INTO song (number, title, type_coro) VALUES (296, '296. Señor, Tu Me Llamas', 3);
INSERT INTO song (number, title, type_coro) VALUES (297, '297. Cristo Es Mi Canción', 3);
INSERT INTO song (number, title, type_coro) VALUES (298, '298. Yo Iré De La Tierra Hasta El Fin', 3);
INSERT INTO song (number, title, type_coro) VALUES (299, '299. ¡Oh Mi Dios, Oh Rey Eterno!', 3);
INSERT INTO song (number, title, type_coro) VALUES (300, '300. Mi Dios, Señor Del Mundo', 3);
INSERT INTO song (number, title, type_coro) VALUES (301, '301. Por Veredas Extraviadas Mal Halle', 3);
INSERT INTO song (number, title, type_coro) VALUES (302, '302. Aprisa, ¡Sión!', 3);
INSERT INTO song (number, title, type_coro) VALUES (303, '303. Entre El Vaivén De La Ciudad', 3);
INSERT INTO song (number, title, type_coro) VALUES (304, '304. Amor Es', 3);
INSERT INTO song (number, title, type_coro) VALUES (305, '305. En Ti, Jesús, Dulce Es Pensar', 3);
INSERT INTO song (number, title, type_coro) VALUES (306, '306. Tiende Tu Mano', 3);
INSERT INTO song (number, title, type_coro) VALUES (307, '307. Mas Cerca, Oh Dios, De Ti', 3);
INSERT INTO song (number, title, type_coro) VALUES (308, '308. Del Señor El Pueblo Somos', 3);
INSERT INTO song (number, title, type_coro) VALUES (309, '309. Quiero Ser Leal', 3);
INSERT INTO song (number, title, type_coro) VALUES (310, '310. Me Seréis Santos', 3);
INSERT INTO song (number, title, type_coro) VALUES (311, '311. Oh Dios, Mi Soberano Rey', 3);
INSERT INTO song (number, title, type_coro) VALUES (312, '312. Ten Compasión De Mi', 3);
INSERT INTO song (number, title, type_coro) VALUES (313, '313. Los Que Esperan En Jehová', 3);
INSERT INTO song (number, title, type_coro) VALUES (314, '314. Dios, Yo Quiero Ser Cristiano', 3);
INSERT INTO song (number, title, type_coro) VALUES (315, '315. Más De Jesús Quiero Aprender', 3);
INSERT INTO song (number, title, type_coro) VALUES (316, '316. Dios De Amor, Te Imploramos', 3);
INSERT INTO song (number, title, type_coro) VALUES (317, '317. A Jesús Pertenecemos', 3);
INSERT INTO song (number, title, type_coro) VALUES (318, '318. Quiero Seguir', 3);
INSERT INTO song (number, title, type_coro) VALUES (319, '319. Dulce Comunión', 3);
INSERT INTO song (number, title, type_coro) VALUES (320, '320. La Paz, El Don De Mi Dios', 3);
INSERT INTO song (number, title, type_coro) VALUES (321, '321. Satisfecho Estoy', 3);
INSERT INTO song (number, title, type_coro) VALUES (322, '322. Habladme Más De Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (323, '323. En Jesucristo, El Rey De Paz', 3);
INSERT INTO song (number, title, type_coro) VALUES (324, '324. Un Eterno Y Grande Amor', 3);
INSERT INTO song (number, title, type_coro) VALUES (325, '325. Yo Sé A Quien He Creído', 3);
INSERT INTO song (number, title, type_coro) VALUES (326, '326. Escogido Fui De Dios', 3);
INSERT INTO song (number, title, type_coro) VALUES (327, '327. Seguridad', 3);
INSERT INTO song (number, title, type_coro) VALUES (328, '328. El Profundo Amor De Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (329, '329. El Rey De Amor Es Mi Pastor', 3);
INSERT INTO song (number, title, type_coro) VALUES (330, '330. Alcance Salvación', 3);
INSERT INTO song (number, title, type_coro) VALUES (331, '331. Todas Las Promesas Del Señor Jesús', 3);
INSERT INTO song (number, title, type_coro) VALUES (332, '332. Confío Yo En Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (333, '333. Cristo, Fiel Te Quiero Ser', 3);
INSERT INTO song (number, title, type_coro) VALUES (334, '334. Paz Con Dios Busque Ganarla', 3);
INSERT INTO song (number, title, type_coro) VALUES (336, '336. Yo Te Seguiré', 3);
INSERT INTO song (number, title, type_coro) VALUES (335, '335. Mas Blanco Que La Nieve', 3);
INSERT INTO song (number, title, type_coro) VALUES (337, '337. Desde El Cielo Cristo Llama', 3);
INSERT INTO song (number, title, type_coro) VALUES (338, '338. ¡Oh Amor Que Excede A Todos!', 3);
INSERT INTO song (number, title, type_coro) VALUES (339, '339. ¡Oh Cristo!, Tu Ayuda Quisiera Tener', 3);
INSERT INTO song (number, title, type_coro) VALUES (340, '340. Salvador, A Ti Me Entrego', 3);
INSERT INTO song (number, title, type_coro) VALUES (341, '341. Tu Cruz Levanta Y Ven Tras Mi', 3);
INSERT INTO song (number, title, type_coro) VALUES (342, '342. Jesús, Yo He Prometido', 3);
INSERT INTO song (number, title, type_coro) VALUES (343, '343. Jesús, Del Hombre Hijo', 3);
INSERT INTO song (number, title, type_coro) VALUES (344, '344. Su Voluntad Da Gozo', 3);
INSERT INTO song (number, title, type_coro) VALUES (345, '345. Puedo Oír Tu Voz', 3);
INSERT INTO song (number, title, type_coro) VALUES (346, '346. Cristo De Todo Es Rey', 3);
INSERT INTO song (number, title, type_coro) VALUES (347, '347. Tuyo Soy, Jesús', 3);
INSERT INTO song (number, title, type_coro) VALUES (348, '348. Consagraos, Oh Cristianos', 3);
INSERT INTO song (number, title, type_coro) VALUES (349, '349. Heme Aquí, Oh Señor', 3);
INSERT INTO song (number, title, type_coro) VALUES (350, '350. Tuyo Soy', 3);
INSERT INTO song (number, title, type_coro) VALUES (351, '351. ¿Cuántos Pueden?', 3);
INSERT INTO song (number, title, type_coro) VALUES (352, '352. Yo Soy Peregrino', 3);
INSERT INTO song (number, title, type_coro) VALUES (353, '353. Contigo, Cristo, Quiero Andar', 3);
INSERT INTO song (number, title, type_coro) VALUES (354, '354. ¡Tengo Un Amigo!', 3);
INSERT INTO song (number, title, type_coro) VALUES (355, '355. ¡Oh! Amor Que No Me Dejara', 3);
INSERT INTO song (number, title, type_coro) VALUES (356, '356. Lejos De Mi Padre Dios', 3);
INSERT INTO song (number, title, type_coro) VALUES (357, '357. Abre Mis Ojos A La Luz', 3);
INSERT INTO song (number, title, type_coro) VALUES (358, '358. Vivo Por Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (359, '359. Haz Lo Que Quieras', 3);
INSERT INTO song (number, title, type_coro) VALUES (360, '360. Tu Mundo Hoy', 3);
INSERT INTO song (number, title, type_coro) VALUES (361, '361. Oh, Señor, Recíbeme Cual Soy', 3);
INSERT INTO song (number, title, type_coro) VALUES (362, '362. Anhelo Trabajar Por El Señor', 3);
INSERT INTO song (number, title, type_coro) VALUES (363, '363. Consagración', 3);
INSERT INTO song (number, title, type_coro) VALUES (364, '364. Día En Día', 3);
INSERT INTO song (number, title, type_coro) VALUES (365, '365. Que Mi Vida Entera Esté', 3);
INSERT INTO song (number, title, type_coro) VALUES (366, '366. Ten Fe En Dios', 3);
INSERT INTO song (number, title, type_coro) VALUES (367, '367. Cristo, En Ti Confío', 3);
INSERT INTO song (number, title, type_coro) VALUES (368, '368. Cristo Me Ayuda Por El A Vivir', 3);
INSERT INTO song (number, title, type_coro) VALUES (369, '369. Ven, Alma Que Lloras', 3);
INSERT INTO song (number, title, type_coro) VALUES (370, '370. Corazones Siempre Alegres', 3);
INSERT INTO song (number, title, type_coro) VALUES (371, '371. Cuan Firme Cimiento', 3);
INSERT INTO song (number, title, type_coro) VALUES (372, '372. La Mano Del Salvador', 3);
INSERT INTO song (number, title, type_coro) VALUES (373, '373. Buscad Primero', 3);
INSERT INTO song (number, title, type_coro) VALUES (374, '374. Mi Dios Reí Mando Esta', 3);
INSERT INTO song (number, title, type_coro) VALUES (375, '375. ¡Salve, Jesús, Mi Redentor!', 3);
INSERT INTO song (number, title, type_coro) VALUES (376, '376. Del Amor Divino', 3);
INSERT INTO song (number, title, type_coro) VALUES (377, '377. ¡Oh Cuan Dulce Es Fiar En Cristo!', 3);
INSERT INTO song (number, title, type_coro) VALUES (378, '378. Redimido Por Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (379, '379. Refugio De Este Pecador', 3);
INSERT INTO song (number, title, type_coro) VALUES (380, '380. Mi Fe Descansa En Buen Lugar', 3);
INSERT INTO song (number, title, type_coro) VALUES (381, '381. Te Necesito Ya', 3);
INSERT INTO song (number, title, type_coro) VALUES (382, '382. Fe La Victoria Es', 3);
INSERT INTO song (number, title, type_coro) VALUES (383, '383. Nunca Desmayar', 3);
INSERT INTO song (number, title, type_coro) VALUES (384, '384. Cual Pendón Hermoso', 3);
INSERT INTO song (number, title, type_coro) VALUES (385, '385. Abismado En El Pecado', 3);
INSERT INTO song (number, title, type_coro) VALUES (386, '386. Que Mi Vida Entera Esté', 3);
INSERT INTO song (number, title, type_coro) VALUES (387, '387. Vienen A Mi', 3);
INSERT INTO song (number, title, type_coro) VALUES (388, '388. No Tengo Temor', 3);
INSERT INTO song (number, title, type_coro) VALUES (389, '389. Objeto De Mi Fe', 3);
INSERT INTO song (number, title, type_coro) VALUES (390, '390. Habla, Jesús, A Mi Alma', 3);
INSERT INTO song (number, title, type_coro) VALUES (391, '391. Quien Quiera Fuerte Mostrarse', 3);
INSERT INTO song (number, title, type_coro) VALUES (392, '392. A Jesús Prefiero', 3);
INSERT INTO song (number, title, type_coro) VALUES (393, '393. ¿Soy Yo Soldado De Jesús?', 3);
INSERT INTO song (number, title, type_coro) VALUES (394, '394. ¿Soy Yo Soldado De Jesús?', 3);
INSERT INTO song (number, title, type_coro) VALUES (395, '395. No Te De Temor Hablar Por Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (396, '396. Si Fui Motivo De Dolor', 3);
INSERT INTO song (number, title, type_coro) VALUES (397, '397. Firmes Y Adelante', 3);
INSERT INTO song (number, title, type_coro) VALUES (398, '398. Mirad Y Ved A Nuestro Dios', 3);
INSERT INTO song (number, title, type_coro) VALUES (399, '399. En Los Negocios Del Rey', 3);
INSERT INTO song (number, title, type_coro) VALUES (400, '400. Tu Vida, ¡Oh Salvador!', 3);
INSERT INTO song (number, title, type_coro) VALUES (401, '401. Estad Por Cristo Firmes', 3);
INSERT INTO song (number, title, type_coro) VALUES (402, '402. ¡Oh Dios De Amor Perfecto!', 3);
INSERT INTO song (number, title, type_coro) VALUES (403, '403. Padre Amoroso, Preside La Boda', 3);
INSERT INTO song (number, title, type_coro) VALUES (404, '404. Hogar Feliz, Donde El Señor Reside', 3);
INSERT INTO song (number, title, type_coro) VALUES (405, '405. Danos Un Bello Hogar', 3);
INSERT INTO song (number, title, type_coro) VALUES (406, '406. Amigo Del Hogar', 3);
INSERT INTO song (number, title, type_coro) VALUES (407, '407. Tu, Que A La Mujer Honraste', 3);
INSERT INTO song (number, title, type_coro) VALUES (408, '408. Loor Por Las Madres', 3);
INSERT INTO song (number, title, type_coro) VALUES (409, '409. ¡Oh Que Amigo Nos Es Cristo!', 3);
INSERT INTO song (number, title, type_coro) VALUES (410, '410. Debes Orar', 3);
INSERT INTO song (number, title, type_coro) VALUES (411, '411. En El Huerto De Oración', 3);
INSERT INTO song (number, title, type_coro) VALUES (412, '412. Getsemaní', 3);
INSERT INTO song (number, title, type_coro) VALUES (413, '413. ¡Oh Dulce, Grata Oración!', 3);
INSERT INTO song (number, title, type_coro) VALUES (414, '414. ¡Piedad, Oh Santo Dios!', 3);
INSERT INTO song (number, title, type_coro) VALUES (415, '415. Nuestra Oración', 3);
INSERT INTO song (number, title, type_coro) VALUES (416, '416. Mi Corazón Elevo A Ti', 3);
INSERT INTO song (number, title, type_coro) VALUES (417, '417. Oh Padre De La Humanidad', 3);
INSERT INTO song (number, title, type_coro) VALUES (418, '418. Dilo A Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (419, '419. Soy Feliz En El Servicio Del Señor', 3);
INSERT INTO song (number, title, type_coro) VALUES (420, '420. Mas Santidad Dame', 3);
INSERT INTO song (number, title, type_coro) VALUES (421, '421. Yo Te Sirvo', 3);
INSERT INTO song (number, title, type_coro) VALUES (422, '422. Para Andar Con Jesús', 3);
INSERT INTO song (number, title, type_coro) VALUES (423, '423. Pronto La Noche Viene', 3);
INSERT INTO song (number, title, type_coro) VALUES (424, '424. A Ti, Señor, Nuestra Canción', 3);
INSERT INTO song (number, title, type_coro) VALUES (425, '425. Ven Y Da Tus Diezmos', 3);
INSERT INTO song (number, title, type_coro) VALUES (426, '426. Juntos Marchamos', 3);
INSERT INTO song (number, title, type_coro) VALUES (427, '427. Mi Vida Di Por Ti', 3);
INSERT INTO song (number, title, type_coro) VALUES (428, '428. Fiel Mayordomo Seré', 3);
INSERT INTO song (number, title, type_coro) VALUES (429, '429. ¡Cuan Grande Amor!', 3);
INSERT INTO song (number, title, type_coro) VALUES (430, '430. Dulces Melodías Cantaré', 3);
INSERT INTO song (number, title, type_coro) VALUES (431, '431. Todas Tus Ancias Y Pesar', 3);
INSERT INTO song (number, title, type_coro) VALUES (432, '432. Fue Sentado A Los Pies De Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (433, '433. Hoy, Ayer Y Por Los Siglos', 3);
INSERT INTO song (number, title, type_coro) VALUES (434, '434. La Gloria De Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (435, '435. Aleluya', 3);
INSERT INTO song (number, title, type_coro) VALUES (436, '436. Yo Tengo Un Himno Que Entonar', 3);
INSERT INTO song (number, title, type_coro) VALUES (437, '437. Amor, Amor', 3);
INSERT INTO song (number, title, type_coro) VALUES (438, '438. El Placer De Mi Alma', 3);
INSERT INTO song (number, title, type_coro) VALUES (439, '439. Qué Lindo Es Cantar', 3);
INSERT INTO song (number, title, type_coro) VALUES (440, '440. El Cristo De Nazaret', 3);
INSERT INTO song (number, title, type_coro) VALUES (441, '441. Gozo, Paz Y Amor', 3);
INSERT INTO song (number, title, type_coro) VALUES (442, '442. Día Feliz', 3);
INSERT INTO song (number, title, type_coro) VALUES (443, '443. Sentir Más Grande Amor', 3);
INSERT INTO song (number, title, type_coro) VALUES (444, '444. Comprado Por Sangre De Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (445, '445. Hay Un Canto Alegre', 3);
INSERT INTO song (number, title, type_coro) VALUES (446, '446. Cristo En Todo Es Señor', 3);
INSERT INTO song (number, title, type_coro) VALUES (447, '447. De Jesús El Nombre Guarda', 3);
INSERT INTO song (number, title, type_coro) VALUES (448, '448. Dios Es Amor', 3);
INSERT INTO song (number, title, type_coro) VALUES (449, '449. Junto A Ti, Mi Buen Señor', 3);
INSERT INTO song (number, title, type_coro) VALUES (450, '450. Dios Te Ama', 3);
INSERT INTO song (number, title, type_coro) VALUES (451, '451. No Hay Cual Jesús', 3);
INSERT INTO song (number, title, type_coro) VALUES (454, '454. ¡Cuan Glorioso Es Mi Cristo!', 3);
INSERT INTO song (number, title, type_coro) VALUES (452, '452. Cantare La Bella Historia', 3);
INSERT INTO song (number, title, type_coro) VALUES (453, '453. Es De Dios La Santa Gracia', 3);
INSERT INTO song (number, title, type_coro) VALUES (455, '455. Suenan Melodías En Mi Ser', 3);
INSERT INTO song (number, title, type_coro) VALUES (456, '456. Dime La Historia De Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (457, '457. Cristo Es Mi Dulce Salvador', 3);
INSERT INTO song (number, title, type_coro) VALUES (458, '458. Junto A La Cruz', 3);
INSERT INTO song (number, title, type_coro) VALUES (459, '459. Ya Pertenezco A Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (460, '460. Porque Él Vive', 3);
INSERT INTO song (number, title, type_coro) VALUES (461, '461. Es Todo Para Mí', 3);
INSERT INTO song (number, title, type_coro) VALUES (462, '462. Canten Con Alegría', 3);
INSERT INTO song (number, title, type_coro) VALUES (463, '463. ¿Sabes Por Qué Canto A Cristo?', 3);
INSERT INTO song (number, title, type_coro) VALUES (464, '464. Grato Es Contar La Historia', 3);
INSERT INTO song (number, title, type_coro) VALUES (465, '465. Grande Gozo Hay En Mi Alma Hoy', 3);
INSERT INTO song (number, title, type_coro) VALUES (466, '466. Victoria En Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (467, '467. Ven A Cristo, Ven Ahora', 3);
INSERT INTO song (number, title, type_coro) VALUES (468, '468. Hallé Un Buen Amigo', 3);
INSERT INTO song (number, title, type_coro) VALUES (469, '469. ¡Que Salvador Es Mi Cristo Jesús!', 3);
INSERT INTO song (number, title, type_coro) VALUES (470, '470. Invitación De Dulce Amor', 3);
INSERT INTO song (number, title, type_coro) VALUES (471, '471. En Pecados Y Temor', 3);
INSERT INTO song (number, title, type_coro) VALUES (472, '472. Es La Vida De Mi Alma', 3);
INSERT INTO song (number, title, type_coro) VALUES (473, '473. Cuan Admirable Es Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (474, '474. He Decidido Seguir A Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (475, '475. Mi Salvador En Su Bondad', 3);
INSERT INTO song (number, title, type_coro) VALUES (476, '476. Al Trono Excelso', 3);
INSERT INTO song (number, title, type_coro) VALUES (477, '477. Paz, Paz, Cuan Dulce Paz', 3);
INSERT INTO song (number, title, type_coro) VALUES (478, '478. Amoroso Salvador', 3);
INSERT INTO song (number, title, type_coro) VALUES (479, '479. Cantar Nos Gusta Unidos', 3);
INSERT INTO song (number, title, type_coro) VALUES (481, '481. Cuanto Mas Le Sirvo', 3);
INSERT INTO song (number, title, type_coro) VALUES (482, '482. Lugar Hay Donde Descansar', 3);
INSERT INTO song (number, title, type_coro) VALUES (480, '480. Solo Cristo Salva', 3);
INSERT INTO song (number, title, type_coro) VALUES (483, '483. Hay Un Nombre Nuevo En La Gloria', 3);
INSERT INTO song (number, title, type_coro) VALUES (484, '484. ¿Cómo Podré Estar Triste?', 3);
INSERT INTO song (number, title, type_coro) VALUES (485, '485. Cantare Loor A Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (486, '486. Cada Día Que Pasa', 3);
INSERT INTO song (number, title, type_coro) VALUES (487, '487. Las Pisadas Del Maestro', 3);
INSERT INTO song (number, title, type_coro) VALUES (488, '488. ¿Deberá Jesús Llevar Su Cruz?', 3);
INSERT INTO song (number, title, type_coro) VALUES (489, '489. La Vida Se Va Como El Viento', 3);
INSERT INTO song (number, title, type_coro) VALUES (490, '490. ¡Oh! Yo Quiero Andar Con Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (491, '491. Evidencias Del Perdón De Dios', 3);
INSERT INTO song (number, title, type_coro) VALUES (492, '492. Cuan Gloriosa Será La Mañana', 3);
INSERT INTO song (number, title, type_coro) VALUES (493, '493. Mi Corazón, Oh Examina Hoy', 3);
INSERT INTO song (number, title, type_coro) VALUES (494, '494. Cuando Mis Luchas Terminen Aquí', 3);
INSERT INTO song (number, title, type_coro) VALUES (495, '495. Jerusalén, Mi Hogar Feliz', 3);
INSERT INTO song (number, title, type_coro) VALUES (496, '496. Yo Podré Reconocerle', 3);
INSERT INTO song (number, title, type_coro) VALUES (497, '497. Unidad Eterna', 3);
INSERT INTO song (number, title, type_coro) VALUES (498, '498. Canten Del Amor De Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (499, '499. Voy Al Cielo, Soy Peregrino', 3);
INSERT INTO song (number, title, type_coro) VALUES (500, '500. En Presencia Estar De Cristo', 3);
INSERT INTO song (number, title, type_coro) VALUES (501, '501. Por El Valle Iremos En Paz', 3);
INSERT INTO song (number, title, type_coro) VALUES (502, '502. Hay Un Lugar Do Quiero Estar', 3);
INSERT INTO song (number, title, type_coro) VALUES (503, '503. Allí No Habrá Tribulación', 3);
INSERT INTO song (number, title, type_coro) VALUES (505, '505. ¡Oh Profundo, Inmenso Amor!', 3);
INSERT INTO song (number, title, type_coro) VALUES (504, '504. Cuando Allá Se Pase Lista', 3);
INSERT INTO song (number, title, type_coro) VALUES (506, '506. Hasta Ese Día', 3);
INSERT INTO song (number, title, type_coro) VALUES (507, '507. Tras El Ocaso', 3);
INSERT INTO song (number, title, type_coro) VALUES (508, '508. Hay Un Mundo Feliz Mas Allá', 3);
INSERT INTO song (number, title, type_coro) VALUES (509, '509. Feliz, Feliz Cumpleaños', 3);
INSERT INTO song (number, title, type_coro) VALUES (510, '510. Con Gran Gozo Y Placer', 3);
INSERT INTO song (number, title, type_coro) VALUES (511, '511. Cristo Me Ama', 3);
INSERT INTO song (number, title, type_coro) VALUES (512, '512. Te Exaltare, Mi Dios, Mi Rey', 3);
INSERT INTO song (number, title, type_coro) VALUES (513, '513. Venid, Nuestras Voces Alegres Unamos', 3);
INSERT INTO song (number, title, type_coro) VALUES (514, '514. ¡Oh Jóvenes, Venid!', 3);
INSERT INTO song (number, title, type_coro) VALUES (515, '515. Es Cristo El Amigo De Los Niños', 3);
INSERT INTO song (number, title, type_coro) VALUES (516, '516. ¿Qué Te Dare, Maestro?', 3);
INSERT INTO song (number, title, type_coro) VALUES (517, '517. Cual Es Esa Gran Verdad', 3);
INSERT INTO song (number, title, type_coro) VALUES (518, '518. Al Cristo Vivo Sirvo', 3);
INSERT INTO song (number, title, type_coro) VALUES (519, '519. ¡Oh Despleguemos El Pendón!', 3);
INSERT INTO song (number, title, type_coro) VALUES (520, '520. Día De Victoria', 3);
INSERT INTO song (number, title, type_coro) VALUES (521, '521. Hijos Del Celeste Rey', 3);
INSERT INTO song (number, title, type_coro) VALUES (522, '522. Usa Mi Vida', 3);
INSERT INTO song (number, title, type_coro) VALUES (523, '523. Dios Te Bendiga', 3);
INSERT INTO song (number, title, type_coro) VALUES (524, '524. Da Lo Mejor Al Maestro', 3);
INSERT INTO song (number, title, type_coro) VALUES (525, '525. 1 Juan 1', 3);
INSERT INTO song (number, title, type_coro) VALUES (526, '526. Se Acerca Un Año Nuevo', 3);
INSERT INTO song (number, title, type_coro) VALUES (527, '527. Gloría Patri', 3);
INSERT INTO song (number, title, type_coro) VALUES (528, '528. A Dios El Padre Celestial', 3);